sonar.projectKey=tanahara0310_CoreEngine
sonar.organization=tanahara0310

sonar.sources=Project

sonar.inclusions=**/*.cpp,**/*.h,**/*.hpp,**/*.hlsl
sonar.exclusions=**/Externals/**,**/.vs/**,**/bin/**,**/obj/**
