name: DebugBuild

on:
  push:
    branches:
      - master

env:
  SOLUTION_FILE_PATH: Project/CoreEngine.slnx
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # C++ BuildTools（v145含む可能性あり）をインストール
      - name: Install VS BuildTools
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --quiet --norestart"


      # MSBuildをフルパス指定で実行
      - name: Build
        run: |
           & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" ${{env.SOLUTION_FILE_PATH}} /p:platform=x64,Configuration=${{env.CONFIGURATION}}